### ISSUE TITLE
.Net Core 2 OR .Net Standard 2?

### ISSUE THREAD

**Issue by OmidID** [scheshan/DotNetBlog#9]
Hello @scheshan 
Last night the new version was released. So we should decide for next version.

**Comment by scheshan** [comment]
Hi @OmidID 
I've seen this great news. I will upgrade the project to use .NET Core 2.0 before this weekend. Then I will spend some days to add some front pages, such as "archives" and something else.

**Comment by OmidID** [comment]
@scheshan Nice ;)
